// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1cf05c96-3430-4f47-b73b-4ea1d0076c83",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_iQyFwK8uk",
    "aws_user_pools_web_client_id": "73po0ga330ns4n9n17ikbh8ulu",
    "aws_appsync_graphqlEndpoint": "https://2lwxvfo5hnalxpgeembgqdnuzq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
